import assert from "node:assert/strict";
import { test } from "node:test";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { closeDatabase, getDatabase } from "../src/lib/db";
import { addItems, archiveTote, createTote, deleteTote, DomainError, getExportSnapshot, getTote, recordPhoto, takeItem } from "../src/lib/inventory";
import { acceptAISuggestions, claimAIRun, completeAIRun, createAIRun, dismissAISuggestions, failAIRun, getAIState, nextQueuedAIRunId, normalizedItemName, restoreAISuggestions } from "../src/lib/ai";
import type { AIRunDTO, ToteDetailDTO } from "../src/lib/contracts";

test("local AI reviews preserve inventory and accept exactly once", async (t) => {
  const directory = await mkdtemp(path.join(tmpdir(), "inventory-ai-test-"));
  const previousDirectory = process.env.INVENTORY_DATA_DIR;
  const previousAI = process.env.AI_URL;
  process.env.INVENTORY_DATA_DIR = directory;
  process.env.AI_URL = "http://127.0.0.1:11434";
  const rejected = (status: number, work: () => unknown) => assert.throws(work, error => error instanceof DomainError && error.status === status);
  const attachPhoto = (id: string) => recordPhoto(id, { id: randomUUID(), originalName: "top-down.jpg", mimeType: "image/jpeg" });
  const photographedTote = (name: string) => attachPhoto(createTote({ name }).id);
  const start = (detail: ToteDetailDTO, force = false) => createAIRun(detail.tote.id, { photoId: detail.tote.photo!.id, contentsUpdatedAt: detail.tote.contentsUpdatedAt, force });
  const ready = (detail: ToteDetailDTO, items: { name: string; quantity: number; note: string }[]): AIRunDTO => {
    const result = start(detail, true);
    assert.ok(result.created);
    assert.ok(result.state.run);
    assert.ok(claimAIRun(result.state.run.id));
    completeAIRun(result.state.run.id, { items });
    const run = getAIState(detail.tote.id).run;
    assert.ok(run);
    assert.equal(run.status, "ready");
    return run;
  };
  const selection = (run: AIRunDTO, index: number, name = run.suggestions[index].name, quantity = run.suggestions[index].quantity) => ({ suggestionId: run.suggestions[index].id, name, quantity });
  let acceptedRunId = "";
  try {
    await t.test("migration from version 1 preserves QR identity, items, removals, photos, and history", () => {
      const tote = createTote({ name: "Legacy tools" });
      const added = addItems(tote.id, { items: [{ name: "Extension cord", quantity: 4 }] });
      takeItem(added.items[0].id, { toteId: tote.id, quantity: 1 });
      attachPhoto(tote.id);
      const before = getTote(tote.id);
      closeDatabase();
      const legacy = new Database(path.join(directory, "inventory.sqlite"));
      legacy.exec("DROP TABLE ai_suggestion_runs");
      legacy.pragma("user_version = 1");
      legacy.close();
      assert.deepEqual(getTote(tote.id), before);
      assert.equal(getDatabase().pragma("user_version", { simple: true }), 4);
      assert.equal(getDatabase().pragma("foreign_keys", { simple: true }), 1);
      assert.equal((getDatabase().prepare("SELECT COUNT(*) AS count FROM ai_suggestion_runs").get() as { count: number }).count, 0);
      assert.equal(createTote({ name: "After migration" }).code, "T002");
      closeDatabase();
      assert.deepEqual(getTote(tote.id), before);
    });
    await t.test("queued, running, and completed drafts never add inventory", () => {
      const detail = photographedTote("Review only");
      const before = getTote(detail.tote.id);
      const result = start(detail);
      assert.equal(result.created, true);
      assert.equal(result.state.run!.status, "queued");
      assert.deepEqual(getTote(detail.tote.id), before);
      assert.equal(claimAIRun(result.state.run!.id)!.status, "running");
      assert.deepEqual(getTote(detail.tote.id), before);
      completeAIRun(result.state.run!.id, { items: [
        { name: "  Gift   wrap  ", quantity: 2, note: "Check the count" },
        { name: "gift wrap", quantity: 3, note: "Duplicate" },
      ] });
      const run = getAIState(detail.tote.id).run!;
      assert.equal(run.status, "ready");
      assert.equal(run.suggestions.length, 1);
      assert.equal(run.suggestions[0].name, "Gift wrap");
      assert.equal(run.suggestions[0].quantity, 2);
      assert.equal(run.suggestions[0].note, "Check the count");
      assert.deepEqual(getTote(detail.tote.id), before);
    });
    await t.test("duplicate names include stored and taken-out items and rejected batches change nothing", () => {
      const tote = createTote({ name: "Existing items" });
      const added = addItems(tote.id, { items: [{ name: "USB cable", quantity: 2 }, { name: "Scissors", quantity: 1 }] });
      const scissors = added.items.find(item => item.name === "Scissors")!;
      takeItem(scissors.id, { toteId: tote.id, quantity: 1 });
      const detail = attachPhoto(tote.id);
      const run = ready(detail, [
        { name: "usb cable", quantity: 1, note: "" },
        { name: "SCISSORS", quantity: 1, note: "" },
        { name: "Gift wrap", quantity: 2, note: "" },
      ]);
      const before = getTote(tote.id);
      for (const index of [0, 1]) rejected(409, () => acceptAISuggestions(tote.id, { runId: run.id, items: [selection(run, 2), selection(run, index)] }));
      assert.deepEqual(getTote(tote.id), before);
      rejected(409, () => acceptAISuggestions(tote.id, { runId: run.id, items: [selection(run, 0, "New name"), selection(run, 1, " new   NAME ")] }));
      rejected(400, () => acceptAISuggestions(tote.id, { runId: run.id, items: [selection(run, 2), selection(run, 2)] }));
      rejected(400, () => acceptAISuggestions(tote.id, { runId: run.id, items: [{ suggestionId: randomUUID(), name: "Unknown", quantity: 1 }] }));
      assert.throws(() => acceptAISuggestions(tote.id, { runId: run.id, items: [selection(run, 2, "Gift wrap", 1.5)] }));
      assert.deepEqual(getTote(tote.id), before);
      assert.equal(getAIState(tote.id).run!.status, "ready");
      assert.equal(normalizedItemName("  \uFF35\uFF33\uFF22   CABLE "), "usb cable");
    });
    await t.test("photo replacement, contents changes, and archive prevent stale acceptance", () => {
      const photoDetail = photographedTote("Changed photo");
      const photoRun = ready(photoDetail, [{ name: "Tape", quantity: 1, note: "" }]);
      attachPhoto(photoDetail.tote.id);
      const afterPhoto = getTote(photoDetail.tote.id);
      assert.equal(getAIState(photoDetail.tote.id).run!.stale, true);
      rejected(409, () => acceptAISuggestions(photoDetail.tote.id, { runId: photoRun.id, items: [selection(photoRun, 0)] }));
      rejected(409, () => start(photoDetail));
      assert.deepEqual(getTote(photoDetail.tote.id), afterPhoto);
      const itemDetail = photographedTote("Changed contents");
      const itemRun = ready(itemDetail, [{ name: "Tape", quantity: 1, note: "" }]);
      const changed = addItems(itemDetail.tote.id, { items: [{ name: "Manual item", quantity: 1 }] });
      assert.equal(getAIState(itemDetail.tote.id).run!.stale, true);
      rejected(409, () => acceptAISuggestions(itemDetail.tote.id, { runId: itemRun.id, items: [selection(itemRun, 0)] }));
      assert.deepEqual(getTote(itemDetail.tote.id), changed);
      const archivedDetail = photographedTote("Archived review");
      const archivedRun = ready(archivedDetail, [{ name: "Tape", quantity: 1, note: "" }]);
      const archived = archiveTote(archivedDetail.tote.id);
      rejected(409, () => acceptAISuggestions(archivedDetail.tote.id, { runId: archivedRun.id, items: [selection(archivedRun, 0)] }));
      rejected(409, () => start(archived));
      assert.deepEqual(getTote(archivedDetail.tote.id), archived);
    });
    await t.test("individual dismissal persists, blocks hidden acceptance, and can be restored", () => {
      const detail = photographedTote("Dismiss individual");
      const run = ready(detail, [{ name: "Tape", quantity: 1, note: "" }, { name: "Cord", quantity: 2, note: "" }]);
      const before = getTote(detail.tote.id);
      let state = dismissAISuggestions(detail.tote.id, { runId: run.id, suggestionId: run.suggestions[0].id });
      assert.equal(state.run!.dismissed, false);
      assert.deepEqual(state.run!.dismissedSuggestionIds, [run.suggestions[0].id]);
      closeDatabase();
      assert.deepEqual(getAIState(detail.tote.id), state);
      assert.deepEqual(dismissAISuggestions(detail.tote.id, { runId: run.id, suggestionId: run.suggestions[0].id }), state);
      rejected(409, () => acceptAISuggestions(detail.tote.id, { runId: run.id, items: [selection(run, 0)] }));
      rejected(404, () => dismissAISuggestions(detail.tote.id, { runId: run.id, suggestionId: randomUUID() }));
      assert.deepEqual(getTote(detail.tote.id), before);
      state = dismissAISuggestions(detail.tote.id, { runId: run.id, suggestionId: run.suggestions[1].id });
      assert.equal(state.run!.dismissed, true);
      const restored = restoreAISuggestions(detail.tote.id, { runId: run.id });
      assert.equal(restored.run!.dismissed, false);
      assert.deepEqual(restored.run!.dismissedSuggestionIds, []);
      assert.deepEqual(restoreAISuggestions(detail.tote.id, { runId: run.id }), restored);
      assert.equal(acceptAISuggestions(detail.tote.id, { runId: run.id, items: [selection(run, 0)] }).detail.items.length, 1);
    });
    await t.test("dismiss all survives completion without releasing the active lease", () => {
      const detail = photographedTote("Dismiss running");
      const run = start(detail).state.run!;
      assert.ok(claimAIRun(run.id));
      const hidden = dismissAISuggestions(detail.tote.id, { runId: run.id }).run!;
      assert.equal(hidden.status, "running");
      assert.equal(hidden.dismissed, true);
      const waiting = photographedTote("Wait behind hidden");
      const next = start(waiting).state.run!;
      assert.equal(nextQueuedAIRunId(), null);
      assert.equal(claimAIRun(next.id), null);
      completeAIRun(run.id, { items: [{ name: "Wrapped cord", quantity: 1, note: "" }] });
      const finished = getAIState(detail.tote.id).run!;
      assert.equal(finished.status, "ready");
      assert.equal(finished.dismissed, true);
      rejected(409, () => acceptAISuggestions(detail.tote.id, { runId: run.id, items: [selection(finished, 0)] }));
      assert.equal(nextQueuedAIRunId(), next.id);
      const restored = restoreAISuggestions(detail.tote.id, { runId: run.id }).run!;
      assert.equal(restored.status, "ready");
      assert.equal(restored.dismissed, false);
      failAIRun(next.id, "Test complete");
      const retry = start(detail, true).state.run!;
      assert.notEqual(retry.id, run.id);
      assert.equal(retry.dismissed, false);
      assert.deepEqual(retry.dismissedSuggestionIds, []);
      rejected(409, () => restoreAISuggestions(detail.tote.id, { runId: run.id }));
      rejected(404, () => dismissAISuggestions(waiting.tote.id, { runId: retry.id }));
      failAIRun(retry.id, "Test complete");
    });
    await t.test("hiding an accepted review never permits adding it twice", () => {
      const detail = photographedTote("Dismiss accepted");
      const run = ready(detail, [{ name: "Gift ribbon", quantity: 3, note: "" }]);
      const items = [selection(run, 0)];
      const accepted = acceptAISuggestions(detail.tote.id, { runId: run.id, items }).detail;
      dismissAISuggestions(detail.tote.id, { runId: run.id });
      restoreAISuggestions(detail.tote.id, { runId: run.id });
      assert.equal(getAIState(detail.tote.id).run!.status, "accepted");
      assert.deepEqual(acceptAISuggestions(detail.tote.id, { runId: run.id, items }).detail, accepted);
      rejected(409, () => acceptAISuggestions(detail.tote.id, { runId: run.id, items: [selection(run, 0, "New name")] }));
    });
    await t.test("FIFO jobs deduplicate retries and ready results, and only one job can run", () => {
      const first = photographedTote("First pending review");
      const second = photographedTote("Second pending review");
      const original = start(first);
      const same = start(first, true);
      assert.equal(original.created, true);
      assert.equal(same.created, false);
      assert.equal(same.state.run!.id, original.state.run!.id);
      const other = start(second);
      assert.equal(other.created, true);
      assert.equal(getAIState(first.tote.id).run!.queuePosition, 1);
      assert.equal(getAIState(second.tote.id).run!.queuePosition, 2);
      assert.equal(claimAIRun(other.state.run!.id), null);
      const id = original.state.run!.id;
      assert.ok(claimAIRun(id));
      assert.equal(claimAIRun(id), null);
      assert.equal(claimAIRun(other.state.run!.id), null);
      assert.equal(getAIState(second.tote.id).run!.queuePosition, 1);
      completeAIRun(id, { items: [{ name: "Cable", quantity: 1, note: "" }] });
      const cached = start(first);
      assert.equal(cached.created, false);
      assert.equal(cached.state.run!.id, id);
      assert.ok(claimAIRun(other.state.run!.id));
      completeAIRun(other.state.run!.id, { items: [] });
      const fresh = start(first, true);
      assert.equal(fresh.created, true);
      assert.notEqual(fresh.state.run!.id, id);
      rejected(409, () => acceptAISuggestions(first.tote.id, { runId: cached.state.run!.id, items: [selection(cached.state.run!, 0)] }));
      assert.deepEqual(getTote(first.tote.id), first);
      failAIRun(fresh.state.run!.id, "Intentional test failure");
      assert.equal(getAIState(first.tote.id).run!.status, "failed");
    });
    await t.test("expired jobs fail and release the global slot without accepting a late completion", () => {
      const oldDetail = photographedTote("Expired review");
      const old = start(oldDetail).state.run!;
      assert.ok(claimAIRun(old.id));
      getDatabase().prepare("UPDATE ai_suggestion_runs SET expires_at=? WHERE id=?").run("2000-01-01T00:00:00.000Z", old.id);
      const nextDetail = photographedTote("Recovered review");
      const next = start(nextDetail);
      assert.equal(next.created, true);
      const failed = getAIState(oldDetail.tote.id).run!;
      assert.equal(failed.status, "failed");
      assert.match(failed.error!, /interrupted|too long/);
      assert.equal(claimAIRun(old.id), null);
      completeAIRun(old.id, { items: [{ name: "Late result", quantity: 1, note: "" }] });
      assert.equal(getAIState(oldDetail.tote.id).run!.status, "failed");
      assert.equal(getTote(oldDetail.tote.id).items.length, 0);
      failAIRun(next.state.run!.id, "Recovery test complete");
    });
    await t.test("a deleted analysis keeps its independent lease until bounded expiry, without releasing a different job", () => {
      const activeDetail = photographedTote("Deleted active analysis");
      const active = start(activeDetail).state.run!;
      assert.ok(claimAIRun(active.id));
      deleteTote(activeDetail.tote.id);
      const waitingDetail = photographedTote("Wait for deleted analysis");
      const waiting = start(waitingDetail).state.run!;
      assert.equal(nextQueuedAIRunId(), null);
      assert.equal(claimAIRun(waiting.id), null);
      getDatabase().prepare("UPDATE settings SET value=0 WHERE key=?").run("ai_inference_lease:" + active.id);
      assert.equal(nextQueuedAIRunId(), waiting.id);
      assert.ok(claimAIRun(waiting.id));
      completeAIRun(active.id, { items: [] });
      failAIRun(active.id, "Late cleanup");
      assert.ok(getDatabase().prepare("SELECT key FROM settings WHERE key=?").get("ai_inference_lease:" + waiting.id));
      assert.equal(nextQueuedAIRunId(), null);
      completeAIRun(waiting.id, { items: [] });
      assert.equal(nextQueuedAIRunId(), null);
      assert.equal(getDatabase().prepare("SELECT key FROM settings WHERE key GLOB 'ai_inference_lease:*'").get(), undefined);
    });
    await t.test("edited selection is accepted once and lost-response retries remain safe after later changes", () => {
      const detail = photographedTote("Accepted review");
      const run = ready(detail, [{ name: "Cord", quantity: 1, note: "Check length" }, { name: "Paper", quantity: 1, note: "" }]);
      const items = [selection(run, 0, "Extension cord", 3), selection(run, 1, "Gift wrap", 2)];
      const result = acceptAISuggestions(detail.tote.id, { runId: run.id, items });
      acceptedRunId = run.id;
      assert.equal(result.detail.tote.totalQuantity, 5);
      assert.equal(result.detail.items.length, 2);
      assert.equal(result.ai.run!.status, "accepted");
      assert.equal(result.ai.run!.acceptedCount, 2);
      assert.equal(result.detail.history.filter(entry => entry.type === "ai_suggestions_added").length, 1);
      const after = getTote(detail.tote.id);
      const retried = acceptAISuggestions(detail.tote.id, { runId: run.id, items: [...items].reverse() });
      assert.deepEqual(retried.detail, after);
      const whitespaceRetry = items.map(item => ({ ...item, name: " " + item.name.replace(/ /g, "   ") + " " }));
      assert.deepEqual(acceptAISuggestions(detail.tote.id, { runId: run.id, items: whitespaceRetry }).detail, after);
      rejected(409, () => acceptAISuggestions(detail.tote.id, { runId: run.id, items: [{ ...items[0], quantity: 4 }, items[1]] }));
      assert.deepEqual(getTote(detail.tote.id), after);
      const cord = after.items.find(item => item.name === "Extension cord")!;
      const taken = takeItem(cord.id, { toteId: detail.tote.id, quantity: 1 });
      assert.deepEqual(acceptAISuggestions(detail.tote.id, { runId: run.id, items }).detail, taken);
      assert.equal(getTote(detail.tote.id).tote.totalQuantity, 4);
      assert.equal(getTote(detail.tote.id).removals[0].outstandingQuantity, 1);
    });
    await t.test("a late database failure rolls back every item, history entry, and acceptance marker", () => {
      const detail = photographedTote("Atomic review");
      const run = ready(detail, [{ name: "First valid", quantity: 2, note: "" }, { name: "Second rejected", quantity: 3, note: "" }]);
      const selected = run.suggestions.map((item, index) => selection(run, index));
      const sorted = [...selected].sort((a,b) => a.suggestionId.localeCompare(b.suggestionId));
      sorted[0].name = "First valid";
      sorted[1].name = "Second rejected";
      const before = getTote(detail.tote.id);
      getDatabase().exec("CREATE TEMP TRIGGER reject_ai_test_item BEFORE INSERT ON items WHEN NEW.name='Second rejected' BEGIN SELECT RAISE(ABORT,'test late rejection'); END");
      try {
        assert.throws(() => acceptAISuggestions(detail.tote.id, { runId: run.id, items: sorted }), /test late rejection/);
        assert.deepEqual(getTote(detail.tote.id), before);
        const row = getDatabase().prepare("SELECT status,accepted_payload_hash AS hash,accepted_count AS count FROM ai_suggestion_runs WHERE id=?").get(run.id) as { status: string; hash: string | null; count: number };
        assert.deepEqual(row, { status: "ready", hash: null, count: 0 });
      } finally { getDatabase().exec("DROP TRIGGER reject_ai_test_item"); }
      assert.equal(acceptAISuggestions(detail.tote.id, { runId: run.id, items: sorted }).detail.items.length, 2);
    });
    await t.test("JSON exports retain source-photo linkage, generated suggestions, and accepted review data", () => {
      const snapshot = getExportSnapshot();
      assert.equal(snapshot.formatVersion, 3);
      const runs = snapshot.aiSuggestionRuns as { id: string; status: string; photo_id: string; suggestions_json: string; accepted_count: number; accepted_payload_hash: string | null }[];
      const accepted = runs.find(run => run.id === acceptedRunId)!;
      assert.ok(accepted);
      assert.equal(accepted.status, "accepted");
      assert.equal(accepted.accepted_count, 2);
      assert.match(accepted.accepted_payload_hash!, /^[0-9a-f]{64}$/);
      assert.equal(JSON.parse(accepted.suggestions_json).length, 2);
      assert.ok(snapshot.photos.some(photo => (photo as { id: string }).id === accepted.photo_id));
      assert.ok(runs.some(run => run.status === "failed"));
    });
  } finally {
    closeDatabase();
    if (previousDirectory === undefined) delete process.env.INVENTORY_DATA_DIR;
    else process.env.INVENTORY_DATA_DIR = previousDirectory;
    if (previousAI === undefined) delete process.env.AI_URL;
    else process.env.AI_URL = previousAI;
    await rm(directory, { recursive: true, force: true });
  }
});
